version: '3.8'

services:
  admin-panel:
    image: react-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:3000" # Maps port 8081 on the host to 3000 in the container
    environment:
      - NODE_ENV=production
    restart: always
